namespace BarangayPharmaSystem.Models.ViewModels;

/// <summary>View model used by the default Error view generated by ASP.NET Core scaffolding.</summary>
public class ErrorViewModel
{
    public string? RequestId { get; set; }
    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}
